# Generated by Django 4.1 on 2022-08-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreyapellido', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('asunto', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
