# Generated by Django 4.1 on 2022-08-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='lugar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
