# Generated by Django 4.1 on 2022-08-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_document_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesAdmin',
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
