# Generated by Django 4.1 on 2022-08-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_delete_filesadmin_alter_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
