# Generated by Django 4.1 on 2022-08-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_fecha_nacimiento_usuario_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nacimiento',
        ),
    ]
